### ISSUE TITLE
Crash in notifications view

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#227]
Really not sure what causes this, but scrolling down my notifications causes this crash at the moment:

```
time: 1658900787901
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'org.joinmastodon.android.ui.displayitems.StatusDisplayItem$Type org.joinmastodon.android.ui.displayitems.StatusDisplayItem.g()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'org.joinmastodon.android.ui.displayitems.StatusDisplayItem$Type org.joinmastodon.android.ui.displayitems.StatusDisplayItem.g()' on a null object reference
	at org.joinmastodon.android.fragments.e$g.h(:1)
	at me.grishka.appkit.views.UsableRecyclerView$e.h(:2)
	at androidx.recyclerview.widget.RecyclerView$v.I(:15)
	at androidx.recyclerview.widget.h.i(:4)
	at androidx.recyclerview.widget.h.c(:2)
	at androidx.recyclerview.widget.h.d(:4)
	at androidx.recyclerview.widget.h.g(:2)
	at androidx.recyclerview.widget.h.run(:9)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

It crashes at the same spot each time, yet no notification looks particularly suspicious (unlike about a month ago when there was a really long spam post tagging hundreds of people, which also crashed the app). Maybe I can replicate the API call and see if I find anything (or share the result), if that helps?

**Comment by d4f5409d** [comment]
Same issue.

**Comment by sk22** [comment]
I think this might be related to me being a moderator on an instance and the API also returning notifications about reports - which also posed a problem for the Mastodon web frontend: https://github.com/mastodon/mastodon/issues/18909

**Comment by sk22** [comment]
Okay, so the scenario which causes this is the following:
`NotificationListFragment`'s `buildDisplayItems` receives a `Notification` object like this:

* type = "STATUS"
* account = …
* id = "#####"
* status = null

In the next lines, `HeaderStatusDisplayItem titleItem` will be `null`, and since `if(n.status!=null)` fails, the method will try to return an array consisting of a that (null) `HeaderStatusDisplayItem` and an `AccountCardStatusDisplayItem` (which would be wrong for status notifications anyway).

The JSON the API returns for said notification looks like this:

```json
{
  "id": "#####",
  "type": "status",
  "created_at": "2022-11-01T23:59:02.807Z",
  "account": { … },
  "status": null
}
```
