### ISSUE TITLE
IllegalStateException: Fragment HashtagTimelineFragment not attached to Activity

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#336]
This can occur when opening and closing the the hashtag timeline at the wrong time (I suppose, when the timeline hasn't finished loading yet)

(Running latest commit)

```
2022-11-11 02:49:44.181 30269-30269/org.joinmastodon.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.joinmastodon.android, PID: 30269
    java.lang.IllegalStateException: Fragment HashtagTimelineFragment{58beaf1} not attached to Activity
        at android.app.Fragment.getResources(Fragment.java:780)
        at android.app.Fragment.getString(Fragment.java:815)
        at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.buildItems(StatusDisplayItem.java:80)
        at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:29)
        at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:25)
        at org.joinmastodon.android.fragments.BaseStatusListFragment.onAppendItems(BaseStatusListFragment.java:106)
        at me.grishka.appkit.utils.Preloader.onDataLoaded(Preloader.java:86)
        at me.grishka.appkit.fragments.BaseRecyclerFragment.onDataLoaded(BaseRecyclerFragment.java:308)
        at org.joinmastodon.android.fragments.HashtagTimelineFragment.access$000(HashtagTimelineFragment.java:19)
        at org.joinmastodon.android.fragments.HashtagTimelineFragment$1.onSuccess(HashtagTimelineFragment.java:40)
        at org.joinmastodon.android.fragments.HashtagTimelineFragment$1.onSuccess(HashtagTimelineFragment.java:37)
        at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8108)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by sk22** [comment]
https://user-images.githubusercontent.com/6217438/201245106-4bf32ae1-38b8-4f59-be1b-1b48dbfb5a29.mp4
