### ISSUE TITLE
Crashes with new ImageLoader

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#383]
Can't really reproduce it reliably, but it happens relatively often when e.g. pasting something in the search bar. (In this case, I pasted a non-fediverse link.)

```
2022-11-19 15:15:20.363 26186-26186/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.joinmastodon.android, PID: 26186
    java.lang.IllegalArgumentException: start=0 > end=-1
        at me.grishka.appkit.imageloader.ListImageLoader.loadRange(ListImageLoader.java:48)
        at me.grishka.appkit.imageloader.ListImageLoader.loadRange(ListImageLoader.java:43)
        at me.grishka.appkit.imageloader.ListImageLoaderWrapper.onScroll(ListImageLoaderWrapper.java:256)
        at me.grishka.appkit.imageloader.RecyclerViewDelegate$1.onScrolled(RecyclerViewDelegate.java:84)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5334)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4396)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4022)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2021)
        at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2060)
        at androidx.recyclerview.widget.RecyclerView.scrollBy(RecyclerView.java:1873)
        at org.joinmastodon.android.ui.utils.UiUtils.updateList(UiUtils.java:495)
        at org.joinmastodon.android.fragments.discover.SearchFragment.updateList(SearchFragment.java:175)
        at me.grishka.appkit.utils.Preloader.onDataLoaded(Preloader.java:108)
        at me.grishka.appkit.fragments.BaseRecyclerFragment.onDataLoaded(BaseRecyclerFragment.java:308)
        at org.joinmastodon.android.fragments.discover.SearchFragment.onDataLoaded(SearchFragment.java:185)
        at org.joinmastodon.android.fragments.discover.SearchFragment$1.onSuccess(SearchFragment.java:151)
        at org.joinmastodon.android.fragments.discover.SearchFragment$1.onSuccess(SearchFragment.java:133)
        at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8108)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by grishka** [comment]
And then people ask why the latest appkit is not on maven central. I added this exception specifically as a sanity check thinking that there might be a bug somewhere that would trigger that condition.

**Comment by sk22** [comment]
okay, noted, maybe i shouldn't build it from source and act like the version's ready.

anyway, i'm able to reproduce it like this:
* make sure i have one "recent searches" item
* paste a link, e.g. https://joinmastodon.org
* reset the search
* paste the link again

**Comment by grishka** [comment]
> maybe i shouldn't build it from source and act like the version's ready.

No, it's actually good that you discovered this crash.

**Comment by sk22** [comment]
> > maybe i shouldn't build it from source and act like the version's ready.
> 
> No, it's actually good that you discovered this crash.

(yeah, no, of course, but since my fork is always based on the latest commit on master here, i also import the bleeding-edge bugs, which isn't ideal)

**Comment by grishka** [comment]
TIL I can close issues across repos, heh

**Comment by sk22** [comment]
let's goooo - thanks!
