### ISSUE TITLE
Crash when selecting instance from list on login

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#386]
* Open app/add account
* From the splash screen, select “Log in” or “Get started”
* Select any server from the list
* Watch as the activity dies

Version: Latest from source (30151cafc28be22bc98fe9a51383717dce57f53d)

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.joinmastodon.android, PID: 18790
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at org.joinmastodon.android.fragments.onboarding.InstanceCatalogFragment$6.onSuccess(InstanceCatalogFragment.java:481)
        at org.joinmastodon.android.fragments.onboarding.InstanceCatalogFragment$6.onSuccess(InstanceCatalogFragment.java:469)
        at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8108)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by sk22** [comment]
Exception happening here (`InstanceCatalogFragment.java#481`) – when `currentSearchQuery` is `null`.
```java
if(domain.equals(currentSearchQuery) || currentSearchQuery.equals(redirects.get(domain)) || currentSearchQuery.equals(redirectsInverse.get(domain))){
```

**Comment by grishka** [comment]
Oh. I'll fix it tomorrow, thanks
