### ISSUE TITLE
Crash because of IncompatibleClassChangeError with UiUtils

### ISSUE THREAD

**Issue by Brawaru** [mastodon/mastodon-android#399]
When trying to open account switcher or changing post privacy, and also when scrolling through settings, the app crashes with the `IncompatibleClassChangeError` exception.

<details>
<summary>Logcat slice</summary>

```
11-22 01:32:53.979  6483  6483 D AndroidRuntime: Shutting down VM
11-22 01:32:53.980  6483  6483 E AndroidRuntime: FATAL EXCEPTION: main
11-22 01:32:53.980  6483  6483 E AndroidRuntime: Process: org.joinmastodon.android, PID: 6483
11-22 01:32:53.980  6483  6483 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'org.joinmastodon.android.ui.utils.UiUtils' appears in /data/app/org.joinmastodon.android-1/base.apk)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at org.joinmastodon.android.ui.utils.UiUtils.enablePopupMenuIcons(UiUtils.java:513)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountViewHolder.onBind(AccountSwitcherSheet.java:217)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountViewHolder.onBind(AccountSwitcherSheet.java:179)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at me.grishka.appkit.utils.BindableViewHolder.bind(BindableViewHolder.java:33)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountsAdapter.onBindViewHolder(AccountSwitcherSheet.java:164)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at org.joinmastodon.android.ui.AccountSwitcherSheet$AccountsAdapter.onBindViewHolder(AccountSwitcherSheet.java:146)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at me.grishka.appkit.utils.MergeRecyclerAdapter.onBindViewHolder(MergeRecyclerAdapter.java:123)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7256)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7339)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6197)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6463)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6303)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6299)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2328)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1629)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1589)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:666)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4300)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3677)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.View.measure(View.java:18797)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:606)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-22 01:32:53.980  6483  6483 E AndroidRuntime:        at android.os.Loop
11-22 01:32:53.981  2024  4351 W ActivityManager:   Force finishing activity org.joinmastodon.android/.MainActivity
```

</details>

This is the current git version complied by @sk22 after we triaged https://github.com/sk22/mastodos/issues/60 to be an upstream issue. This is not reproducible using the version that's available right now in Google Play.

Presumably this is the line causing crash:
https://github.com/mastodon/mastodon-android/blob/2c61551e5cef9c8e6f111a036832494fbeb08375/mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java#L513

This is an unofficial CyanPop build running Android 6.0.1, but I got no other device. It works perfectly fine otherwise, so perhaps there's some other way to avoid not invoking that code if try-catch is not working. Or, if you don't want to bother and dismiss it as an unsupported version, that's okay too, but probably would make sense to raise system requirements then.

**Comment by grishka** [comment]
I will test on a Nexus 5 running stock Android 6.0 later this week and probably some more 6.0 devices. If it doesn't crash on any of them, then it must be caused by your custom ROM.

**Comment by grishka** [comment]
No, I'm unable to reproduce it. But then I only own a single device that runs 6.0 (but probably some others can be downgraded but I'm too lazy to do that) and I probably can't run a 6.0 emulator on an m1 mac.

![Screenshot_20221126_194233](https://user-images.githubusercontent.com/1478258/204099472-a41d5f7a-98ed-4e4f-b664-ee982cb56a2a.png)

**Comment by grishka** [comment]
They do have ARM64 images all the way down to 5.0 now, nice. Doesn't reproduce there either.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/1478258/204099771-8185f749-c02f-4853-955b-4c1715fb33f6.png">

**Comment by Brawaru** [comment]
Oh, I guess that's my ROM issue then, weird. Is this code present in the stable build that is currently in Play Store by the way? (Closing as ‘won't fix’ in a meanwhile)

**Comment by Brawaru** [comment]
Okay, in latest Play Store version it does not crash either and from code it doesn't seem like you changed anything. I wonder if it's @sk22 builds that bugged then?
