### ISSUE TITLE
Crashing when backgrounded on Android 13

### ISSUE THREAD

**Issue by ThePowerOfDreams** [mastodon/mastodon-android#452]
```
type: crash
osVersion: google/redfin/redfin:13/TQ1A.221205.011/2022120700:user/release-keys
package: org.joinmastodon.android:45
process: org.joinmastodon.android
processUptime: 22340 + 773 ms

o1.f: Unable to find generated Parcelable class for v0.i0$l, verify that your class is configured properly and that the Parcelable class v0.i0$l$$Parcelable is generated by Parceler.
	at o1.g$b.c(:8)
	at o1.g.b(:1)
	at o1.g.c(:1)
	at v0.i0.onSaveInstanceState(:13)
	at android.app.Fragment.performSaveInstanceState(Fragment.java:2691)
	at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2676)
	at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2737)
	at android.app.FragmentController.saveAllState(FragmentController.java:119)
	at android.app.Activity.onSaveInstanceState(Activity.java:2299)
	at s.a.onSaveInstanceState(:5)
	at android.app.Activity.performSaveInstanceState(Activity.java:2221)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1601)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5792)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5190)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5156)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5221)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

**Comment by grishka** [comment]
Which app version is this? Is this an official build or did you build it yourself?

**Comment by ThePowerOfDreams** [comment]
Straight out of the Play Store, 1.1.4.

Android is GrapheneOS TQ1A.221205.011.2022120700
