### ISSUE TITLE
Crashing when adding more than one image attachment

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon-android#453]
User reporting that the Android app crashes when they add more than one image attachment.

They have tried attaching different images, restarting the app, restarting the phone and reinstalling the app, but the problem persists.

Version is Mastodon for Android v1.1.4 (45)

**Comment by grishka** [comment]
I'm unable to reproduce this.

**Comment by MedzikUser** [comment]
logs from `adb logcat`

```
  73   | 12-12 17:11:12.270 20413 20413 E AndroidRuntime: FATAL EXCEPTION: main
  74   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime: Process: org.joinmastodon.android, PID: 20413
  75   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime: o1.f: Unable to find generated Parcelable class for v0.i0$l, verify that your class is configured properly and that the Parcelable class v0.i0$l$$Parcelable is generated by Parceler.
  76   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at o1.g$b.c(:8)
  77   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at o1.g.b(:1)
  78   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at o1.g.c(:1)
  79   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at v0.i0.onSaveInstanceState(:13)
  80   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.Fragment.performSaveInstanceState(Fragment.java:2691)
  81   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2676)
  82   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2737)
  83   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.FragmentController.saveAllState(FragmentController.java:119)
  84   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.Activity.onSaveInstanceState(Activity.java:2293)
  85   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at s.a.onSaveInstanceState(:5)
  86   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.Activity.performSaveInstanceState(Activity.java:2214)
  87   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1522)
  88   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6031)
  89   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5428)
  90   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5394)
  91   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5459)
  92   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
  93   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
  94   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
  95   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  96   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
  97   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
  98   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.os.Looper.loopOnce(Looper.java:233)
  99   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:344)
 100   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:8248)
 101   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
 102   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
 103   │ 12-12 17:11:12.270 20413 20413 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
 ```

**Comment by MedzikUser** [comment]
This error only appears when you add photos one at a time.

**Comment by olekstomek** [comment]
> This error only appears when you add photos one at a time.

Yes, but it means that is not a problem? 
https://github.com/mastodon/mastodon-android/issues/522
