### ISSUE TITLE
Cutting text in compose fragment crashes the app

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#498]
As in sk22#270:

Cutting the `#world` from a text like `hello #world` crashes the app. I don't understand what exactly crashes it and what doesn't, but from what I can tell, it appears to be related to "special text" like hashtags or custom emoji.

```
java.lang.IndexOutOfBoundsException: charAt: 2 >= length 2
	at android.text.SpannableStringBuilder.charAt(Unknown Source:56)
	at android.text.CharSequenceCharacterIterator.current(Unknown Source:12)
	at android.text.CharSequenceCharacterIterator.setIndex(Unknown Source:10)
	at android.icu.text.RuleBasedBreakIterator.CISetIndex32(RuleBasedBreakIterator.java:1055)
	at android.icu.text.RuleBasedBreakIterator.isBoundary(RuleBasedBreakIterator.java:549)
	at android.text.method.WordIterator.isBoundary(Unknown Source:5)
	at android.widget.Editor$SelectionHandleView.positionAtCursorOffset(Unknown Source:12)
	at android.widget.Editor$HandleView.invalidate(Unknown Source:15)
	at android.widget.Editor$SelectionModifierCursorController.invalidateHandles(Unknown Source:4)
	at android.widget.Editor.invalidateHandlesAndActionMode(Unknown Source:4)
	at android.widget.TextView.spanChange(Unknown Source:183)
	at android.widget.TextView$ChangeWatcher.onSpanRemoved(Unknown Source:8)
	at android.text.SpannableStringBuilder.sendSpanRemoved(Unknown Source:14)
	at android.text.SpannableStringBuilder.removeSpan(Unknown Source:85)
	at android.text.SpannableStringBuilder.removeSpan(Unknown Source:17)
	at android.text.SpannableStringBuilder.removeSpan(Unknown Source:1)
	at v0.i0$d.onTextChanged(:18)
	at android.widget.TextView.sendOnTextChanged(Unknown Source:19)
	at android.widget.TextView.handleTextChanged(Unknown Source:68)
	at android.widget.TextView$ChangeWatcher.onTextChanged(Unknown Source:2)
	at android.text.SpannableStringBuilder.sendTextChanged(Unknown Source:12)
	at android.text.SpannableStringBuilder.replace(Unknown Source:255)
	at android.text.SpannableStringBuilder.delete(Unknown Source:7)
	at android.text.SpannableStringBuilder.delete(Unknown Source:0)
	at android.widget.TextView.deleteText_internal(Unknown Source:4)
	at android.widget.TextView.onTextContextMenuItem(Unknown Source:158)
	at org.joinmastodon.android.ui.views.ComposeEditText.onTextContextMenuItem(:4)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Unknown Source:72)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(Unknown Source:2)
	at miuix.toolbar.FloatingActionModeHelper$ActionModeCallback2Wrapper.onActionItemClicked(Unknown Source:2)
	at miuix.toolbar.FloatingActionMode$3.onMenuItemSelected(Unknown Source:8)
	at miuix.toolbar.internal.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source:4)
	at miuix.toolbar.internal.menu.MenuItemImpl.invoke(Unknown Source:18)
	at miuix.toolbar.internal.menu.MenuBuilder.performItemAction(Unknown Source:13)
	at miuix.toolbar.FloatingActionMode$4.onMenuItemClick(Unknown Source:15)
	at miuix.toolbar.internal.FloatingToolbar$3.onClick(Unknown Source:28)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:108)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

```

**Comment by grishka** [comment]
Oh ffs the bugs with this autocomplete thing are never gonna end, are they 😭

**Comment by sk22** [comment]
i don't know 😩

**Comment by grishka** [comment]
At this point I'm close to just wrapping the whole thing into a try-catch so it never crashes again.

**Comment by grishka** [comment]
But then also I'd rather avoid doing that unless as a last resort because (as [some other apps show](https://github.com/DrKLO/Telegram)) this sometimes results in things breaking in mysterious ways, complicating debugging

**Comment by grishka** [comment]
It turns out you aren't supposed to touch the Editable from onTextChanged

**Comment by sk22** [comment]
huh, weird. thanks for fixing it!
