### ISSUE TITLE
HomeTimelineFragment crashes onPause

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#512]
```
java.lang.RuntimeException: Unable to pause activity {org.joinmastodon.android.git/org.joinmastodon.android.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=73; index=-1
	at android.app.ActivityThread.performPauseActivityIfNeeded(Unknown Source:124)
	at android.app.ActivityThread.performPauseActivity(Unknown Source:82)
	at android.app.ActivityThread.handlePauseActivity(Unknown Source:12)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(Unknown Source:110)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(Unknown Source:10)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(Unknown Source:25)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:79)
	at android.app.ClientTransactionHandler.executeTransaction(Unknown Source:7)
	at android.app.ActivityThread.handleRelaunchActivityLocally(Unknown Source:85)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:157)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:108)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=73; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at org.joinmastodon.android.fragments.HomeTimelineFragment.onHidden(HomeTimelineFragment.java:151)
	at me.grishka.appkit.fragments.AppKitFragment.onPause(AppKitFragment.java:513)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onPause(BaseStatusListFragment.java:607)
	at android.app.Fragment.performPause(Unknown Source:13)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:800)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:38)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:46)
	at android.app.FragmentManagerImpl.dispatchMoveToState(Unknown Source:12)
	at android.app.FragmentManagerImpl.dispatchPause(Unknown Source:1)
	at android.app.Fragment.performPause(Unknown Source:4)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:800)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:38)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:46)
	at android.app.FragmentManagerImpl.dispatchMoveToState(Unknown Source:12)
	at android.app.FragmentManagerImpl.dispatchPause(Unknown Source:1)
	at android.app.FragmentController.dispatchPause(Unknown Source:4)
	at android.app.Activity.performPause(Unknown Source:45)
	at android.app.Instrumentation.callActivityOnPause(Unknown Source:0)
	at android.app.ActivityThread.performPauseActivityIfNeeded(Unknown Source:20)
	... 16 more
```

**Comment by sk22** [comment]
not sure if this happens on every "onPause" or what the conditions are, i can only say that i've had the app crash at least twice (i think it paused while attaching the debugger) with this crash log
