### ISSUE TITLE
[Question] how to run the tests?

### ISSUE THREAD

**Issue by giuliohome** [mastodon/mastodon-android#542]
Thank you for the awesome work.
Tried building with Android Studio and the apk was ok (even though I used latest AS and jdk and a fake signature). I only changed the jdk from AS as per your suggestion in [another issue](https://github.com/mastodon/mastodon-android/issues/241) and I upgraded the gradle plugin.

My question about the [tests](https://github.com/mastodon/mastodon-android/blob/master/mastodon/src/androidTest/java/org/joinmastodon/android/test/StoreScreenshotsGenerator.java) because I couldn't run them at first trial: are you using Espresso tests, can them be built and executed from Android Studio, should I tweak anything in gradle settings to make them work?

Thank you again

**Comment by grishka** [comment]
The tests don't actually test anything. They generate screenshots for Google Play. That's all they do, there are no assertions. You don't need to run them unless you want these screenshots.

**Comment by giuliohome** [comment]
yes, I understand, I'm just interested in these testing aspects, now I've noticed that there is something like a test instrumented apk that I could maybe move to a cloud testing environment... OK, thank you, I don't want to waste your time if this is not relevant for the project, we can close this question, keep up with the good work! 😃

**Comment by giuliohome** [comment]
Cool, I see the Screenshot Clusters from Firebase Test Lab!

![immagine](https://user-images.githubusercontent.com/3272563/223423474-42fa0083-ac9f-4471-a82a-6feb444b3bac.png)

![immagine](https://user-images.githubusercontent.com/3272563/223423600-68597afb-bff9-4ccb-9f56-53c85c86ff22.png)

![immagine](https://user-images.githubusercontent.com/3272563/223423801-42347c1d-1cd9-4175-a156-ac27a502b8a9.png)

etc...

🆒 👍

**Comment by giuliohome** [comment]
FYI

this is the log of the exception

![image](https://user-images.githubusercontent.com/3272563/223511601-c371000c-1889-4a61-bc6e-a7336239a025.png)


```
java.lang.AssertionError: Activity never becomes requested state "[DESTROYED, CREATED, STARTED, RESUMED]" (last lifecycle transition = "PRE_ON_CREATE")
at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:353)
at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:279)
at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:197)
at androidx.test.ext.junit.rules.ActivityScenarioRule.lambda$new$0(ActivityScenarioRule.java:73)
at androidx.test.ext.junit.rules.ActivityScenarioRule$$ExternalSyntheticLambda2.get(Unknown Source:2)
at androidx.test.ext.junit.rules.ActivityScenarioRule.before(ActivityScenarioRule.java:106)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:438)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2213)
```

not sure if [this](https://stackoverflow.com/questions/68332390/changing-from-deprecated-activitytestrule-to-activityscenariorule-breaks-test) is related or which could be the root cause, reopening only to ask your opinion about that.

**Comment by giuliohome** [comment]
[Allowed autostart and pop-up window for this app ](https://stackoverflow.com/a/69053805/21013193)on my android phone settings. Solved the above exception but it still fails 

```
java.lang.IllegalStateException: Account session null not found
at org.joinmastodon.android.api.session.AccountSessionManager.getAccount(AccountSessionManager.java:141)
at org.joinmastodon.android.test.StoreScreenshotsGenerator.takeScreenshots(StoreScreenshotsGenerator.java:84)
```

shell cmd

```
[giulio@fedora mastodon-android]$ sudo ./gradlew connectedAndroidTest 
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (14) JDWP2dHandshake
07:41:06 V/JdwpProxy-Buffer: DEVICE WRITE (19) 00013400000ￇ1REAQ0000
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (99) 000cﾀ0010ￇ1APNM000P0001103c0p0r0e02d0i0n0i0t0i0a0l0i0z0e0d03e00000001103c0p0r0e02d0i0n0i0t0i0a0l0i0z0e0d03e
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (147) 000ﾓﾀ0020ￇ1APNM000ﾀ0001d0o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d02e0t0e0s0t00000001d0o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d02e0t0e0s0t
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (20) 0001440000ﾀ00REAQ00010
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (132) 000ﾄ40001ﾀ00HELO000q000100dh000d00000D0a0l0v0i0k0200v0202e0102e000000000e060402d0b0i0t0200280a0r0m0604029000d0C0h0e0c0k0J0N0I03d0t0r0u0e00000
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (341) 001U40002ﾀ00FEAT001B0007000190h0p0r0o0f02d0h0e0a0p02d0d0u0m0p02d0s0t0r0e0a0m0i0n0g000f0h0p0r0o0f02d0h0e0a0p02d0d0u0m0p000170m0e0t0h0o0d02d0s0a0m0p0l0e02d0p0r0o0f0i0l0i0n0g000200m0e0t0h0o0d02d0t0r0a0c0e02d0p0r0o0f0i0l0i0n0g02d0s0t0r0e0a0m0i0n0g000160m0e0t0h0o0d02d0t0r0a0c0e02d0p0r0o0f0i0l0i0n0g000e0v0i0e0w02d0h0i0e0r0a0r0c0h0y000e0o0p0e0n0g0l02d0t0r0a0c0i0n0g
07:41:06 V/JdwpProxy-Buffer: DEVICE WRITE (19) 00013400030ￇ1MPRQ0000
07:41:06 V/JdwpProxy-Buffer: CLIENT WRITE (20) 0001440003ﾀ00MPRQ00010
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
07:41:12 V/JdwpProxy-Buffer: DEVICE WRITE (14) JDWP2dHandshake
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (14) JDWP2dHandshake
07:41:12 V/JdwpProxy-Buffer: DEVICE WRITE (19) 00013400050ￇ1REAQ0000
07:41:12 V/JdwpProxy-Buffer: DEVICE WRITE (23) 00017400060ￇ1HELO00040001
07:41:12 V/JdwpProxy-Buffer: DEVICE WRITE (19) 00013400070ￇ1FEAT0000
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (127) 0007fﾀ0020ￇ1APNM000l000180o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d0000000180o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d
07:41:12 V/JdwpProxy-Buffer: DEVICE WRITE (19) 00013400080ￇ1MPRQ0000
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (20) 0001440005ﾀ00REAQ00010
07:41:12 V/JdwpProxy-Buffer: DEVICE WRITE (20) 00014400090ￇ1HPIF00010
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (228) 000ffffffe440006ﾀ00HELO000ffffffd10001001016000d000180D0a0l0v0i0k0200v0202e0102e000o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d0000000e060402d0b0i0t0200280a0r0m0604029000d0C0h0e0c0k0J0N0I03d0t0r0u0e0000180o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (341) 001U40007ﾀ00FEAT001B0007000190h0p0r0o0f02d0h0e0a0p02d0d0u0m0p02d0s0t0r0e0a0m0i0n0g000f0h0p0r0o0f02d0h0e0a0p02d0d0u0m0p000170m0e0t0h0o0d02d0s0a0m0p0l0e02d0p0r0o0f0i0l0i0n0g000200m0e0t0h0o0d02d0t0r0a0c0e02d0p0r0o0f0i0l0i0n0g02d0s0t0r0e0a0m0i0n0g000160m0e0t0h0o0d02d0t0r0a0c0e02d0p0r0o0f0i0l0i0n0g000e0v0i0e0w02d0h0i0e0r0a0r0c0h0y000e0o0p0e0n0g0l02d0t0r0a0c0i0n0g
07:41:12 V/JdwpProxy-Buffer: CLIENT WRITE (20) 0001440008ﾀ00MPRQ00010
07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
07:41:13 V/JdwpProxy-Buffer: DEVICE WRITE (14) JDWP2dHandshake
07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (4) OKAY
07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (14) JDWP2dHandshake
07:41:13 V/JdwpProxy-Buffer: DEVICE WRITE (19) 000134000a0ￇ1REAQ0000
07:41:13 V/JdwpProxy-Buffer: DEVICE WRITE (23) 000174000b0ￇ1HELO00040001
07:41:13 V/JdwpProxy-Buffer: DEVICE WRITE (19) 000134000c0ￇ1FEAT0000
07:41:13 V/JdwpProxy-Buffer: DEVICE WRITE (19) 000134000d0ￇ1MPRQ0000
07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (20) 000144000aﾀ00REAQ00010
07:41:13 V/JdwpProxy-Buffer: DEVICE WRITE (20) 000144000e0ￇ1HPIF00010
07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (200) 000ffffffc84000bﾀ00HELO000ﾵ000100103e000d000110D0a0l0v0i0k0200v0202e0102e0003c0p0r0e02d0i0n0i0t0i0a0l0i0z0e0d03e0000000e060402d0b0i0t0200280a0r0m0604029000d0C0h0e0c0k0J0N0I03d0t0r0u0e00001103c0p0r0e02d0i0n0i0t0i0a0l0i0z0e0d03e
07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (341) 001U4000cﾀ00FEAT001B0007000190h0p0r0o0f02d0h0e0a0p02d0d0u0m0p02d0s0t0r0e0a0m0i0n0g000f0h0p0r0o0f02d0h0e0a0p02d0d0u0m0p000170m0e0t0h0o0d02d0s0a0m0p0l0e02d0p0r0o0f0i0l0i0n0g000200m0e0t0h0o0d02d0t0r0a0c0e02d0p0r0o0f0i0l0i0n0g02d0s0t0r0e0a0m0i0n0g000160m0e0t0h0o0d02d0t0r0a0c0e02d0p0r0o0f0i0l0i0n0g000e0v0i0e0w02d0h0i0e0r0a0r0c0h0y000e0o0p0e0n0g0l02d0t0r0a0c0i0n0g
07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (20) 000144000dﾀ00MPRQ00010

> Task :mastodon:connectedDebugAndroidTest
Starting 1 tests on Redmi Note 8T - 11

07:41:13 V/JdwpProxy-Buffer: CLIENT WRITE (147) 000ﾓﾀ0020ￇ1APNM000ﾀ0001d0o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d02e0t0e0s0t00000001d0o0r0g02e0j0o0i0n0m0a0s0t0o0d0o0n02e0a0n0d0r0o0i0d02e0t0e0s0t

> Task :mastodon:connectedDebugAndroidTest

org.joinmastodon.android.test.StoreScreenshotsGenerator > takeScreenshots[Redmi Note 8T - 11] FAILED 
        java.lang.IllegalStateException: Account session null not found
        at org.joinmastodon.android.api.session.AccountSessionManager.getAccount(AccountSessionManager.java:141)
Tests on Redmi Note 8T - 11 failed: There was 1 failure(s).

> Task :mastodon:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mastodon:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/giulio/android-setup/mastodon-android/mastodon/build/reports/androidTests/connected/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
56 actionable tasks: 1 executed, 55 up-to-date
```

**Comment by grishka** [comment]
I've never tried running these tests in any kind of server environment or form the command line, so what you're trying to do might never work. I ran them locally on an emulator from within Android Studio.

The last exception says that there's no account logged into the app. You need to install the app, run it normally, and log into an account before you run these tests.

**Comment by giuliohome** [comment]
Thanks for your reply.

**Tried after I've manually logged** in with my account and now I see

```
androidx.test.espresso.PerformException: Error performing 'wait for a specific view with id <2131165208> during 5000 millis.' on view 'Animations or transitions are enabled on the target device.
For more info check: https://developer.android.com/training/testing/espresso/setup#set-up-environment

view.getRootView() to equal view'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
at androidx.test.espresso.base.PerformExceptionHandler.handleSafely(PerformExceptionHandler.java:8)
at androidx.test.espresso.base.PerformExceptionHandler.handleSafely(PerformExceptionHandler.java:9)
at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
at org.joinmastodon.android.test.StoreScreenshotsGenerator.takeScreenshots(StoreScreenshotsGenerator.java:103)
... 33 trimmed
Caused by: java.util.concurrent.TimeoutException
at org.joinmastodon.android.test.StoreScreenshotsGenerator$3.perform(StoreScreenshotsGenerator.java:245)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:25)
at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:5)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8057)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

I'm running the test locally
