### ISSUE TITLE
Crash when removing an uploaded attachment when removing an already uploaded one

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#558]
```
java.lang.IllegalStateException: there is already an attachment being uploaded
	at org.joinmastodon.android.fragments.ComposeFragment.uploadMediaAttachment(ComposeFragment.java:1457)
	at org.joinmastodon.android.fragments.ComposeFragment.uploadNextQueuedAttachment(ComposeFragment.java:1620)
	at org.joinmastodon.android.fragments.ComposeFragment.onRemoveMediaAttachmentClick(ComposeFragment.java:1550)
	at org.joinmastodon.android.fragments.ComposeFragment.$r8$lambda$1hRhUNBp5ec52ShpsobSVmXt2ZY(Unknown Source:0)
	at org.joinmastodon.android.fragments.ComposeFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:108)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
```

(crash log is from megalodon, bug occurs on mastodon too)

**Comment by grishka** [comment]
Duplicate of #557

**Comment by sk22** [comment]
oops, sorry!
