### ISSUE TITLE
2.5.4 (106) from F-Droid always crashes on start

### ISSUE THREAD

**Issue by SkewedZeppelin** [mastodon/mastodon-android#859]
is also minified, not sure if proguard mapping is available
```
07-04 17:24:24.519 27402 27402 D AndroidRuntime: Shutting down VM
07-04 17:24:24.519 27402 27402 E AndroidRuntime: FATAL EXCEPTION: main
07-04 17:24:24.519 27402 27402 E AndroidRuntime: Process: org.joinmastodon.android, PID: 27402
07-04 17:24:24.519 27402 27402 E AndroidRuntime: java.lang.ExceptionInInitializerError
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.api.session.d0.t(SourceFile:1)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.MainActivity.C(SourceFile:1)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.MainActivity.onCreate(SourceFile:9)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8342)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8321)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.joinmastodon.android.api.i0 org.joinmastodon.android.api.session.d0.z()' on a null object reference
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.api.MastodonAPIRequest.k(SourceFile:7)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.api.session.d0.Q(SourceFile:15)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.api.session.d0.H(SourceFile:44)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.api.session.d0.K(SourceFile:116)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.api.session.d0.<init>(SourceFile:169)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	at org.joinmastodon.android.api.session.d0.<clinit>(SourceFile:3)
07-04 17:24:24.519 27402 27402 E AndroidRuntime: 	... 21 more
07-04 17:24:24.520  1363  7863 I am_crash: [27402,10,org.joinmastodon.android,551075396,java.lang.NullPointerException,Attempt to invoke virtual method 'org.joinmastodon.android.api.i0 org.joinmastodon.android.api.session.d0.z()' on a null object reference,SourceFile,7]
07-04 17:24:24.521  1363  7863 
```

**Comment by grishka** [comment]
Yes it does, that's the reason why I removed this release. You should update to 2.5.6.

**Comment by SkewedZeppelin** [comment]
Yes, I just realized that, apologies.

**Comment by licaon-kter** [comment]
@grishka any blockers to report this to F-Droid?

**Comment by grishka** [comment]
What do you mean? Is there some process I'm supposed to follow? The current version doesn't crash.

**Comment by licaon-kter** [comment]
Yes, as OP did above, open an issue to announce _"hey, the app is crashing, don't build it, don't host it, don't update users with a crashing app"_

Or plain ping me or @linsui somewhere

Or ping floss.social/@fdroidorg

Or send a message in a bottle

Anything

**Comment by grishka** [comment]
Ok, noted

**Comment by licaon-kter** [comment]
Thanks, I've disabled that version, but it will take one cycle for the update to come (this running one) and another one for the bad one to go away.
