### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by TheBiostarfly** [mastodon/mastodon-android#896]
I just update the app to 2.7. and the app keeps crashing when I try to open it! 

I'm on GrapheneOS without Google play support!

I'm including the logs hoping it will help:

```
type: crash
osVersion: google/oriole/oriole:14/AP2A.240905.003.F1/2024092900:user/release-keys
package: org.joinmastodon.android:119
process: org.joinmastodon.android
processUptime: 90 + 247 ms
installer: com.looker.droidify

java.lang.ExceptionInInitializerError
	at org.joinmastodon.android.MainActivity.C(SourceFile:1)
	at org.joinmastodon.android.MainActivity.onCreate(SourceFile:9)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.UnsupportedOperationException: h
	at o.f.e(SourceFile:11)
	at org.joinmastodon.android.api.session.AccountSession.<init>(SourceFile:13)
	at org.joinmastodon.android.api.session.AccountSessionManager.lambda$new$0(SourceFile:35)
	at org.joinmastodon.android.api.session.AccountSessionManager.c(SourceFile:1)
	at org.joinmastodon.android.api.session.x.a(SourceFile:1)
	at org.joinmastodon.android.api.session.AccountSessionManager.runWithDatabase(SourceFile:11)
	at org.joinmastodon.android.api.session.AccountSessionManager.<init>(SourceFile:70)
	at org.joinmastodon.android.api.session.AccountSessionManager.<clinit>(SourceFile:3)
	... 21 more
```

**Comment by grishka** [comment]
Please install the latest release from Github releases. Someone must have republished a bad build that I briefly made available.

**Comment by TheBiostarfly** [comment]
It's the IzzyOnDroid version 🤷‍♂️

**Comment by grishka** [comment]
Okay it's actually another crash

**Comment by TheBiostarfly** [comment]
@izzysoft

**Comment by grishka** [comment]
This build https://github.com/mastodon/mastodon-android/actions/runs/11170110424/artifacts/2013267341 should have this crash fixed.

**Comment by TheBiostarfly** [comment]
Awesome! Thank you for the quick fix!
