### ISSUE TITLE
2.7.0 crash directly at Startup

### ISSUE THREAD

**Issue by s4msy** [mastodon/mastodon-android#902]
Installed update, direct crash at startup. Cleared cache, nothing. Removed App-Data okay, that works. Relogin into account use the app like normal. Stopped the app. Crash again.

Here is my log.

```
type: crash
osVersion: google/lynx/lynx:14/AP2A.240905.003/2024092900:user/release-keys
package: org.joinmastodon.android:119
process: org.joinmastodon.android
processUptime: 80 + 246 ms
installer: com.android.packageinstaller

java.lang.ExceptionInInitializerError
	at org.joinmastodon.android.MainActivity.C(SourceFile:1)
	at org.joinmastodon.android.MainActivity.onCreate(SourceFile:9)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.UnsupportedOperationException: h
	at o.f.e(SourceFile:11)
	at org.joinmastodon.android.api.session.AccountSession.<init>(SourceFile:13)
	at org.joinmastodon.android.api.session.AccountSessionManager.lambda$new$0(SourceFile:35)
	at org.joinmastodon.android.api.session.AccountSessionManager.c(SourceFile:1)
	at org.joinmastodon.android.api.session.x.a(SourceFile:1)
	at org.joinmastodon.android.api.session.AccountSessionManager.runWithDatabase(SourceFile:11)
	at org.joinmastodon.android.api.session.AccountSessionManager.<init>(SourceFile:70)
	at org.joinmastodon.android.api.session.AccountSessionManager.<clinit>(SourceFile:3)
	... 21 more

```

**Comment by s4msy** [comment]
Downloaded 2.7.1 from Izzy Repo and looks like error is resolved.
