### ISSUE TITLE
crash when trying to view notifications

### ISSUE THREAD

**Issue by SkewedZeppelin** [mastodon/mastodon-android#913]
version 2.7.3 from f-droid.org

```
10-25 17:46:35.060 30305 30305 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.joinmastodon.android.model.Account.id' on a null object reference in method 'void h1.q.U1(org.joinmastodon.android.model.viewmodel.NotificationViewModel)'
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at h1.q.U1(SourceFile:21)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at h1.q.e1(SourceFile:3)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at h1.c0.i(SourceFile:20)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at h1.n4.i(SourceFile:1)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at l0.h.d(SourceFile:88)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at g0.f.A0(SourceFile:29)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at h1.n4.k2(SourceFile:1)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at h1.n4$a.a(SourceFile:25)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at h1.n4$a.onSuccess(SourceFile:3)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at org.joinmastodon.android.api.CacheController.Y(SourceFile:10)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at org.joinmastodon.android.api.CacheController.r(SourceFile:1)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at org.joinmastodon.android.api.j.run(SourceFile:1)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-25 17:46:35.060 30305 30305 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
10-25 17:46:35.061  1368  1778 I am_crash: [30305,10,org.joinmastodon.android,551075396,java.lang.NullPointerException,Attempt to read from field 'java.lang.String org.joinmastodon.android.model.Account.id' on a null object reference in method 'void h1.q.U1(org.joinmastodon.android.model.viewmodel.NotificationViewModel)',SourceFile,21]
```

**Comment by rozeboosje** [comment]
"Me too" mastodon app 2.8.0 on Android

**Comment by grishka** [comment]
What about 2.9.0 or 2.9.1?

**Comment by rozeboosje** [comment]
And here I was thinking the app would automatically get updated. Went to Play Store, updated the app, it's now on 2.9.1 and whadyaknow it's back working again.

Cheers

**Comment by antimundo** [comment]
I have the same problem, it crashes when I open the notifications, I'm on Mastodon 2.9.0 (128).

**Comment by antimundo** [comment]
I saw a Mastodon post of another user that had the same problem, I told him to update the app, and he replied that indeed it got fixed after updating the app :)

https://mastodon.social/@Solanus/113498865055324729

**Comment by dadall** [comment]
Hey,

The app is still crashing with 2.9.1. The update fixed the issue during 2 days but it's back again.

Regards

**Comment by grishka** [comment]
Try logging out and back in again.

**Comment by dadall** [comment]
> Try logging out and back in again.

It seems to be ok now  !

**Comment by AndyDearden** [comment]
I've just started getting this on 2.9.5 updated 13th March 2025

Samsung A15 galaxy
One UI 6.1
Android 14

**Comment by grishka** [comment]
It's not "this", it's a different crash that happens when a server returns malformed notification objects (a mention notification without a status object). I have no idea why some servers do that and haven't observed it happen myself, but it does happen for a small number of people somehow. I fixed it today.
